/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#98cbff",
        "surface-dim": "#d8dadb",
        "outline-variant": "#bec8ca",
        "surface-container": "#eceeef",
        "secondary-fixed": "#cfe5ff",
        "secondary": "#00629d",
        "primary-fixed": "#a6eff8",
        "inverse-on-surface": "#eff1f2",
        "background": "#f8fafb",
        "surface": "#f8fafb",
        "outline": "#6f797a",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#004a77",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#543a00",
        "primary": "#00474d",
        "on-background": "#191c1d",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f8fafb",
        "inverse-primary": "#8ad2db",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3f484a",
        "on-primary-container": "#90d8e1",
        "on-primary-fixed-variant": "#004f56",
        "tertiary-fixed": "#ffdea8",
        "on-tertiary-container": "#ffc247",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#271900",
        "on-secondary-container": "#003558",
        "surface-container-low": "#f2f4f5",
        "primary-fixed-dim": "#8ad2db",
        "on-secondary-fixed": "#001d33",
        "secondary-container": "#00a2fd",
        "on-primary-fixed": "#001f23",
        "tertiary-container": "#725000",
        "tertiary-fixed-dim": "#ffba20",
        "surface-tint": "#136870",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#006068",
        "on-tertiary-fixed-variant": "#5e4200",
        "surface-container-high": "#e6e8e9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
